# Generated by Django 6.1.1 on 2026-10-04 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("ciudad", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "estrellas",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hoteles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Huesped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Huésped",
                "verbose_name_plural": "Huéspedes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="TipoHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("precio_noche", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Tipo de habitación",
                "verbose_name_plural": "Tipos de habitación",
                "ordering": ["precio_noche"],
            },
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                ("piso", models.PositiveSmallIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("ocupada", "Ocupada"),
                            ("mantencion", "En mantención"),
                        ],
                        default="disponible",
                        max_length=15,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habitaciones",
                        to="hotel.hotel",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="habitaciones",
                        to="hotel.tipohabitacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habitación",
                "verbose_name_plural": "Habitaciones",
                "ordering": ["hotel", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Recepcionista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recepcionistas",
                        to="hotel.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepcionista",
                "verbose_name_plural": "Recepcionistas",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrada", models.DateField()),
                ("fecha_salida", models.DateField()),
                (
                    "cantidad_huespedes",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("checkin", "Check-in"),
                            ("checkout", "Check-out"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="hotel.habitacion",
                    ),
                ),
                (
                    "huesped",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="hotel.huesped",
                    ),
                ),
                (
                    "recepcionista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="hotel.recepcionista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha_entrada"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="hotel.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.AddConstraint(
            model_name="habitacion",
            constraint=models.UniqueConstraint(
                fields=("hotel", "numero"), name="habitacion_unica_por_hotel"
            ),
        ),
    ]
